# This message is used in a handshake between smap server and smap modules

string name # Name of the module | Name must be unique
string type # Type of the module | 'object' or 'place'
string architecture # Architecture of the module | (e.g.) yolo_v5
uint16 n_classes # Number of classification classes of the detector
string[] classes # Names of classes know by the detector. The names must be ordered to match the int corresponding values
# classes (e.g.) "keyboard;mouse;laptop"
---
bool is_new # If already exists a module with the provided name the result will be false
uint8 module_id # unique id of the module on the server
bool success # Return True if the operation was successfull