name: Build
run-name: CI Build/Test
on:
  push:
      branches:
        - main

jobs:
  Build:
    name: smap_interfaces build
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out smap_interfaces
        uses: actions/checkout@v3
      - name: Building and testing
        uses: ichiro-its/ros2-ci@v1.0.0
        with: 
          ros2-distro: foxy

